extends: semantic-release-monorepo
branches:
  - master
  - name: beta
    prelerease: true
  - name: feature/ci
    prerelease: true
    tags:
      - ci
plugins:
  - semantic-release-gitmoji
  # - - "@semantic-release/npm"
  #   - npmPublish: false
  # - "@semantic-release/github"
  # - "@semantic-release/git"
