extends: semantic-release-monorepo
branches:
  - name: feature/ci
    prerelease: true
plugins:
  - semantic-release-gitmoji
  # - - "@semantic-release/npm"
  #   - npmPublish: false
  # - "@semantic-release/github"
  # - "@semantic-release/git"
